Repository lotteon2/lotdiz-apigateway-service, pull requests merged in 2023-11, with the labels that each got.

#15 release
  .github/workflows/deploy-prod.yml
  deploy-prod.sh
  service-prod.yml
  src/main/java/com/lotdiz/apigatewayservice/filter/OptionalAuthorizationHeaderFilter.java
  src/main/resources/application.yml
Labels: release, pending

#16 add predicate url
  src/main/resources/application.yml
Labels: pending

#20 release
  src/main/resources/application.yml
Labels: release
